trigger:
  branches:
    include:
    - develop
    - test
    - qa
    - main
  paths:
    include:
    - '*'
    exclude:
    - '.devops/*'
    - 'azure-pipelines*.yml'
    - 'README.md'
    - .*
    - Dockerfile
    - package.json
    - package-lock.json

resources:
  repositories:
    - repository: templates
      type: git
      name: 012-Lab-Team BackOffice/BackOffice-DevOps

stages:
# Preparation
- template: .devops/pipeline-templates/stages/preparationStage.yml@templates
  parameters:
    stageName: 'Preparation'
    branchCondition: 'develop'
# Development
- template: .devops/pipeline-templates/stages/defaultStage.yml@templates
  parameters:
    stageName: 'Development'
    branchCondition: 'develop'
    runSonarqube: true
    serviceConnectionContainerRegistry: 'CNRGDSLAB001'
    appServiceName: 'APSV-DS-BO-SSS-001'
    serviceConnectionAPIM: 'sp-lab-dev-002-sharedservices-habilitadores'
    serviceConnectionBackend: 'sp-lab-dev-002-sharedservices-habilitadores'
    rgName: 'RSGR-DS-LAB-007'
    apimExternalName: 'APIMDSLAB001'
    apimInternalName: 'APIMDSLAB002'
    productName: 'portalbo'
    apiPath: 'portalbo-service'
    externalExpose: true
# Testing
- template: .devops/pipeline-templates/stages/defaultStage.yml@templates
  parameters:
    stageName: 'Testing'
    branchCondition: 'test'
    runSonarqube: false
    serviceConnectionContainerRegistry: 'CNRGTSLABSSS001'
    appServiceName: 'APSV-TS-BO-SSS-001'
    serviceConnectionAPIM: 'sp-lab-ts-002-sharedservices-habilitadores'
    serviceConnectionBackend: 'sp-lab-ts-002-sharedservices-habilitadores'
    rgName: 'RSGR-TS-LAB-SSS-001'
    apimExternalName: 'APEX-TS-LAB-SSS-001'
    apimInternalName: 'APIM-TS-LAB-SSS-001'
    productName: 'portalbo'
    apiPath: 'portalbo-service'
    externalExpose: true
# QA
- template: .devops/pipeline-templates/stages/defaultStage.yml@templates
  parameters:
    stageName: 'QA'
    branchCondition: 'qa'
    runSonarqube: false
    serviceConnectionContainerRegistry: 'CNRGQALABSSS001'
    appServiceName: 'APSV-QA-BO-SSS-001'
    serviceConnectionAPIM: 'sp-lab-qa-002-sharedservices-habilitadores'
    serviceConnectionBackend: 'sp-lab-qa-002-sharedservices-habilitadores'
    rgName: 'RSGR-QA-LAB-SSS-001'
    apimExternalName: 'APEX-QA-LAB-SSS-001'
    apimInternalName: 'APIM-QA-LAB-SSS-001'
    productName: 'portalbo'
    apiPath: 'portalbo-service'
    externalExpose: true
# Production
- template: .devops/pipeline-templates/stages/defaultStage.yml@templates
  parameters:
    stageName: 'Production'
    branchCondition: 'main'
    runSonarqube: false
    serviceConnectionContainerRegistry: 'CNRGDSLAB001'
    appServiceName: 'APSV-PR-BO-SSS-001'
    serviceConnectionAPIM: 'sp-lab-pr-002-sharedservices-habilitadores'
    serviceConnectionBackend: 'sp-lab-pr-002-sharedservices-habilitadores'
    rgName: 'RSGR-PR-LAB-SSS-001'
    apimExternalName: 'APEX-PR-LAB-SSS-001'
    apimInternalName: 'APIM-PR-LAB-SSS-002'
    productName: 'portalbo'
    apiPath: 'portalbo-service'
    externalExpose: true